cache: bundler
language: ruby
rvm:
  - 2.3.3
script: bundle exec rake
sudo: false

before_install:
  - gem update --system --no-doc --no-ri
  - gem install bundler

after_script:
  - bundle exec codeclimate-test-reporter

bundler_args: --without development --with ci
